version: '3'

services:
  web:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    container_name: web_app_container
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - ./web_app:/app
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0 --port=5000

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: