version: '3'

services:
  web:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    container_name: web_app_container
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    volumes:
      - ./web_app:/app
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0 --port=5000