name: MongoDB CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull MongoDB image
        run: docker pull mongo

      - name: Tag and push MongoDB image
        run: |
          docker tag mongo dave147/whatscooking-db:latest
          docker push dave147/whatscooking-db:latest
