name: Web App CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint black

      - name: Run linting
        run: pylint web_app/app.py

      - name: Format code with Black
        run: black web_app/

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./web_app
          push: true
          tags: dave147/whatscooking-web:latest

      - name: Deploy to Existing DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            # Navigate to the deployment directory
            cd /root/5-final-7southfrogs

            # Pull the latest images from Docker Hub
            docker pull dave147/whatscooking-web:latest
            docker pull dave147/whatscooking-db:latest

            # Restart the containers using docker-compose
            docker-compose down
            docker-compose up -d
