name: Web App CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        - name: Run linting
          working-directory: ./web_app
          run: pipenv run pylint web_app.py
        
        - name: Format code with Black
          working-directory: ./web_app
          run: pipenv run black .

        # Add testing after building unit tests
        
